spring:
  datasource:
    url: ENC(MSADrPeqSNMWvaOBsyZTzaIb6dQ3Nem29PJ89zAZ33jP8O+sTbu754/hhDQ81goJ)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(KWKo0pSOt1ufRLYjLgnoc1kF0Rihu/CU)
    password: ENC(ZYyGDXZoS5Oe2fUs6MGdRPetOXN/HCGO)

  profiles:
    include: oauth

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor